# Generated by Django 3.0.5 on 2021-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_yuviproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yuviproduct',
            name='like',
            field=models.IntegerField(),
        ),
    ]
